### ISSUE TITLE
库没法引用

### ISSUE THREAD

**Issue by gsc1234567890woshishui** [qindachang/BluetoothLELibrary#1]
Error:(47, 13) Failed to resolve: com.qindachang:BluetoothLELibrary:0.1.0
<a href="openFile:F:/a/InsuranceForOldman/Demogit/MyApplication3/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by davistsin** [comment]
不好意思，是jcenter审核问题。你可以先下载项目文件，通过import model的方式导入library。或者等待明天审核没问题再试试。有什么问题可以直接找我：Q 714275846

**Comment by davistsin** [comment]
库已经可以正常引入，注意将minSdkVersion 设置为 18 以上哦
