### ISSUE TITLE
android 6.0以上ble notify方式 数据丢失挺严重

### ISSUE THREAD

**Issue by pangyu646182805** [qindachang/BluetoothLELibrary#13]
android 6.0以上ble notify方式 数据丢失挺严重
正常1s接受100组数据 结果3s才能接受100组数据
请问有解决办法吗

**Comment by davistsin** [comment]
这个不是数据丢失，接收数据的速率跟APP没有关系，是硬件底层固件设置广播时间间隔，解决办法是跟你们的固件工程师沟通协调解决
