### ISSUE TITLE
请问一下，为什么我下载运行你的demo没有任何反应？

### ISSUE THREAD

**Issue by leguang** [qindachang/BluetoothLELibrary#2]
请问一下，为什么我下载运行你的demo没有任何反应？
我看了你的代码，是用一个textview来显示信息，可是运行起来没有半点反应。

**Comment by davistsin** [comment]
Demo作为编程方式参考。不知你是否将demo中UUID等参数修改为你的蓝牙产品的参数。

**Comment by davistsin** [comment]
我修改了demo中的代码，现在可以查看反应了。
