### ISSUE TITLE
建议 

### ISSUE THREAD

**Issue by huyanghu** [qindachang/BluetoothLELibrary#3]
我想在service中做扫描,你的库就不能用了,你应该把传人的Activity 修改成context就行
     mBluetoothLe.setScanPeriod(20000)
                //   .setScanWithServiceUUID(BluetoothUUID.SERVICE)
                .setReportDelay(0)
                .startScan(this);

**Comment by davistsin** [comment]
Nice suggestion. I will change code that what you issue in next version.
