### ISSUE TITLE
关于mac地址过滤的问题

### ISSUE THREAD

**Issue by shaonialife** [qindachang/BluetoothLELibrary#4]
在 ScanFilter 里面对mac地址进行过滤时，没有忽略大小写，进行开发时扫描出来的是大写mac地址，而服务器给的是小写mac地址，导致匹配不上，没有扫描出对应的设备
if (mDeviceAddress != null
                && (device == null || !mDeviceAddress.equals(device.getAddress()))) {
            return false;
}
建议将 equals()方法改为 忽略大小写的 equalsIgnoreCase() 方法

**Comment by davistsin** [comment]
flowing
