### ISSUE TITLE
请问怎么自动配对？

### ISSUE THREAD

**Issue by wushangjun** [qindachang/BluetoothLELibrary#6]
请问怎么自动配对？

**Comment by davistsin** [comment]
你需要自己去写这套逻辑，或者可以参考下面这段代码：

`
    private void scan() {
        if (!LocationServiceUtils.isOpenLocService(this) && ApiLevelHelper.isAtLeast(Build.VERSION_CODES.N)) {
            Toast.makeText(this, "Android 7.0以上扫描蓝牙，需要地理位置信息。请您开启。", Toast.LENGTH_LONG).show();
            LocationServiceUtils.gotoLocServiceSettings(this);
            return;
        }
        if (mBluetoothLe.getScanning()) {
            Toast.makeText(this,"正在扫描中...",Toast.LENGTH_SHORT).show();
            return;
        }
        mBluetoothLe.setScanWithDeviceName(DEVICE_NAME)
                .setReportDelay(0)
                .startScan(this, new OnLeScanListener() {
                    @Override
                    public void onScanResult(BluetoothDevice bluetoothDevice, int rssi, ScanRecord scanRecord) {
                        mBluetoothDevice = bluetoothDevice;
                        stopScan();
                        connect();
                    }

                    @Override
                    public void onBatchScanResults(List<ScanResult> results) {

                    }

                    @Override
                    public void onScanCompleted() {
                        if (mBluetoothDevice == null) {
                            mTvScanBrasBluetoothNotice.setText("没有搜索到设备\n请确定设备开启未被连接");
                            if (animation != null && animation.hasStarted()) {
                                animation.cancel();
                            }
                        }
                    }

                    @Override
                    public void onScanFailed(ScanBleException e) {

                    }
                });
        mTvScanBrasBluetoothNotice.setText("正在扫描xxx设备...");
        animation = AnimationUtils.loadAnimation(this, R.anim.anim_progress_scan);
        mIvScanBrasBluetoothProgress.setAnimation(animation);
    }

    private void stopScan() {
        mBluetoothLe.stopScan();
    }

    private void connect() {
        mBluetoothLe.startConnect(false, mBluetoothDevice);
    }
`
