### ISSUE TITLE
已连接了设备再去连接其他设备,无法连接

### ISSUE THREAD

**Issue by MisterBowie** [qindachang/BluetoothLELibrary#9]
已连接了设备再去连接其他设备,无法连接,可不可以在连接的状态中连接新的设备

**Comment by davistsin** [comment]
这个库是针对一个蓝牙设备的，只能连接一个设备。如果你需要多设备连接，请转移至：https://github.com/qindachang/BluetoothLE-Multi-Library
同时，多个设备连接，你需要自己去管理你的connector对象，一个对象对应一个蓝牙连接
